import json
import sys

def generate_html(data, filename):
    url = data.get("url", "Unknown")
    score = data.get("score", 100)
    defects = data.get("defects", [])
    tech = data.get("tech_stack_detected", [])
    img_perf = data.get("image_performance", {})
    
    defects_html = "".join([f"<li class='py-2 border-b border-gray-100'><span class='font-semibold text-red-600'>{d['defect']}</span><br><span class='text-gray-600 text-sm'>{d['impact']}</span></li>" for d in defects])
    tech_html = "".join([f"<span class='bg-blue-100 text-blue-800 text-xs font-medium mr-2 px-2.5 py-0.5 rounded dark:bg-blue-900 dark:text-blue-300'>{t}</span>" for t in tech])

    html = f"""
    <!DOCTYPE html>
    <html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Audit: {url}</title>
        <script src="https://cdn.tailwindcss.com"></script>
    </head>
    <body class="bg-gray-50 text-gray-900 p-8">
        <div class="max-w-4xl mx-auto">
            <header class="mb-8">
                <h1 class="text-4xl font-bold text-gray-900">Website Audit Report</h1>
                <p class="text-xl text-gray-500 mt-2">{url}</p>
            </header>

            <div class="grid grid-cols-1 md:grid-cols-3 gap-6 mb-8">
                <div class="bg-white p-6 rounded-xl shadow-sm border border-gray-200">
                    <h2 class="text-sm font-medium text-gray-500 uppercase">Health Score</h2>
                    <p class="text-4xl font-bold mt-2 {'text-green-600' if score >= 80 else 'text-red-600'}">{score}/100</p>
                </div>
                <div class="bg-white p-6 rounded-xl shadow-sm border border-gray-200">
                    <h2 class="text-sm font-medium text-gray-500 uppercase">Defects Found</h2>
                    <p class="text-4xl font-bold mt-2 text-red-600">{len(defects)}</p>
                </div>
                <div class="bg-white p-6 rounded-xl shadow-sm border border-gray-200">
                    <h2 class="text-sm font-medium text-gray-500 uppercase">Images Analyzed</h2>
                    <p class="text-4xl font-bold mt-2 text-blue-600">{img_perf.get('total_images', 0)}</p>
                </div>
            </div>

            <div class="bg-white p-6 rounded-xl shadow-sm border border-gray-200 mb-8">
                <h2 class="text-xl font-bold mb-4">🛠️ Tech Stack Detected</h2>
                <div class="flex flex-wrap gap-2">
                    {tech_html if tech_html else "<span class='text-gray-500'>No specific CMS/Frameworks detected.</span>"}
                </div>
            </div>

            <div class="bg-white p-6 rounded-xl shadow-sm border border-gray-200">
                <h2 class="text-xl font-bold mb-4 text-red-600">🐛 Defects & Impacts</h2>
                <ul class="divide-y divide-gray-200">
                    {defects_html if defects_html else "<li class='py-4 text-green-600 font-bold'>🎉 No defects found!</li>"}
                </ul>
            </div>
            
            <footer class="mt-12 text-center text-gray-400 text-sm">
                Generated by WEBSITE-AUDITOR (Local 2026 Build)
            </footer>
        </div>
    </body>
    </html>
    """
    
    with open(filename, 'w') as f:
        f.write(html)
    print(f"🎨 Dashboard generated! Open this file in your browser: {filename}")

if __name__ == "__main__":
    if len(sys.argv) < 2:
        print("Usage: python3 dashboard.py <audit_report.json>")
        sys.exit(1)
        
    json_file = sys.argv[1]
    with open(json_file, 'r') as f:
        data = json.load(f)
        
    html_filename = json_file.replace('.json', '.html')
    generate_html(data, html_filename)
