import pathlib

pathlib.Path("website_auditor/portal").mkdir(parents=True, exist_ok=True)
pathlib.Path("website_auditor/portal/__init__.py").touch()

code = """
import json, http.server
from pathlib import Path

PORTAL_TEMPLATE = \"\"\"<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>{client_name} - Website Health Report</title>
<style>
  :root {{ --brand: {brand_color}; --bg: #0f172a; --card: #1e293b; --text: #e2e8f0; }}
  * {{ margin: 0; padding: 0; box-sizing: border-box; }}
  body {{ font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif; background: var(--bg); color: var(--text); padding: 2rem; }}
  .header {{ text-align: center; margin-bottom: 2rem; }}
  .header h1 {{ color: var(--brand); font-size: 1.8rem; }}
  .header p {{ opacity: 0.7; margin-top: 0.5rem; }}
  .score-ring {{ width: 120px; height: 120px; border-radius: 50%; border: 8px solid var(--brand);
    display: flex; align-items: center; justify-content: center; margin: 1rem auto; font-size: 2rem; font-weight: bold; }}
  .summary {{ background: var(--card); border-radius: 12px; padding: 1.5rem; margin: 1rem 0; border-left: 4px solid var(--brand); }}
  .defect {{ background: var(--card); border-radius: 8px; padding: 1rem; margin: 0.5rem 0;
    display: flex; justify-content: space-between; align-items: center; }}
  .defect .issue {{ flex: 1; }}
  .defect .risk {{ padding: 0.2rem 0.6rem; border-radius: 4px; font-size: 0.8rem; font-weight: bold; }}
  .risk-high {{ background: #dc2626; color: white; }}
  .risk-medium {{ background: #d97706; color: white; }}
  .risk-low {{ background: #16a34a; color: white; }}
  .footer {{ text-align: center; margin-top: 3rem; opacity: 0.5; font-size: 0.8rem; }}
</style>
</head>
<body>
<div class="header">
  <h1>{agency_name}</h1>
  <h2>Website Health Report: {domain}</h2>
  <p>Prepared for {client_name}</p>
</div>
<div class="score-ring">{score}</div>
<div class="summary">
  <strong>Executive Summary</strong>
  <p>{summary}</p>
</div>
<h3 style="margin: 1.5rem 0 0.5rem;">Detected Issues ({defect_count})</h3>
{defect_rows}
<div class="footer">
  <p>Generated by WEBSITE-AUDITOR Action Engine</p>
</div>
</body>
</html>\"\"\"

class PortalHandler(http.server.SimpleHTTPRequestHandler):
    def do_GET(self):
        if self.path == "/" or self.path == "/report":
            self.send_response(200)
            self.send_header("Content-Type", "text/html")
            self.end_headers()
            self.wfile.write(self.build_report().encode())
        else:
            self.send_response(404)
            self.end_headers()

    def build_report(self):
        remediation_dir = Path("outputs/remediations")
        domain = "example.co.nz"
        defects = []
        score = 0
        if remediation_dir.exists():
            for f in remediation_dir.glob("*.json"):
                if "summary" in f.name: continue
                try:
                    data = json.loads(f.read_text())
                    domain = f.stem.replace("-remediation", "")
                    defects = data.get("defects", data.get("issues", []))
                    score = data.get("score", 0)
                    break
                except Exception: continue
        
        try:
            from website_auditor.ai.summarizer import AISummarizer
            ai = AISummarizer()
            summary_data = ai.generate_summary(domain, defects, score)
            summary = summary_data["summary"]
        except Exception:
            summary = "Your website has been audited. See issues below."

        rows = ""
        for d in defects[:10]:
            issue = d.get("issue", d.get("title", str(d)))
            priority = d.get("priority", 5)
            risk_class = "risk-high" if priority <= 3 else "risk-medium" if priority <= 6 else "risk-low"
            risk_label = "HIGH" if priority <= 3 else "MEDIUM" if priority <= 6 else "LOW"
            rows += f'<div class="defect"><span class="issue">{issue}</span><span class="risk {risk_class}">{risk_label}</span></div>'

        return PORTAL_TEMPLATE.format(
            domain=domain, client_name="Valued Client", agency_name="Your Agency Name",
            brand_color="#06b6d4", score=score, summary=summary,
            defect_count=len(defects), defect_rows=rows or "<p>No defects found.</p>",
        )

def start_portal(port=8080):
    server = http.server.HTTPServer(("127.0.0.1", port), PortalHandler)
    print(f"\\n🌐 Client Portal running at: http://127.0.0.1:{port}")
    print(f"   Press Ctrl+C to stop.\\n")
    try: server.serve_forever()
    except KeyboardInterrupt: 
        print("\\nPortal stopped.")
        server.shutdown()

if __name__ == "__main__":
    start_portal()
"""

pathlib.Path("website_auditor/portal/server.py").write_text(code)
print("✅ server.py created successfully!")
