sonar.projectKey=yabigdd-9_website-auditor
sonar.organization=yabigdd-9
sonar.projectName=Website Auditor
sonar.projectVersion=3.0

sonar.sources=.
sonar.exclusions=**/__pycache__/**,**/.venv/**,**/node_modules/**,**/outputs/**,**/audits/**,**/reports/**,**/test-results/**
sonar.test.exclusions=**/tests/**

sonar.python.version=3.12
sonar.sourceEncoding=UTF-8