"""Generate Markdown and JSON reports for a proof review package.

Produces human-readable Markdown and machine-readable JSON output
from a ProofPackage for reviewer consumption.
"""

from __future__ import annotations

import json
import os
import tempfile
from datetime import datetime, timezone

from auditor_toolkit.proof.schema import ProofPackage


def generate_markdown_report(
    package: ProofPackage,
    output_dir: str | None = None,
) -> str:
    """Generate a Markdown report from a ProofPackage.

    Returns the path to the generated .md file.
    """
    output_dir = output_dir or tempfile.mkdtemp(prefix="website-auditor-proof-")
    os.makedirs(output_dir, exist_ok=True)

    md = _render_markdown_content(package)

    ts = datetime.now(timezone.utc).strftime("%Y%m%dT%H%M%SZ")
    md_path = os.path.join(output_dir, f"report_{ts}.md")
    with open(md_path, "w", encoding="utf-8") as f:
        f.write(md)

    return md_path


def _render_markdown_content(package: ProofPackage) -> str:
    v = package.verification
    fix = package.proposed_fix
    before = package.before
    after = package.after
    verdict_badge = {
        "FIXED": "✅ FIXED",
        "NOT_FIXED": "❌ NOT FIXED",
        "REGRESSION": "⚠️ REGRESSION",
        "INCONCLUSIVE": "❓ INCONCLUSIVE",
        "INVALID": "🚫 INVALID",
    }.get(v.verdict, v.verdict)

    return f"""# Proof Report — {package.package_id}

**Finding:** {package.finding_id}
**URL:** {package.url}
**Status:** {package.status}
**Generated:** {package.created_at or datetime.now(timezone.utc).isoformat()}

---

## Verdict

| Result |
|--------|
| {verdict_badge} |

**Confidence:** {v.confidence:.0%}
**Verifier:** {v.verifier_id}

---

{_render_proposed_fix(fix)}

## Before State

| Field | Value |
|-------|-------|
| Status | {before.status} |
| Captured at | {before.captured_at or "N/A"} |
| Screenshot | `{before.screenshot.path or "N/A"}` |
| DOM snapshot | `{before.dom_snapshot.html_path or "N/A"}` |
| Axe violations | {len(before.axe_violations)} |
| Console errors | {len(before.console_errors)} |
| Network failures | {len(before.network_requests)} |

---

## After State

| Field | Value |
|-------|-------|
| Status | {after.status} |
| Captured at | {after.captured_at or "N/A"} |
| Screenshot | `{after.screenshot.path or "N/A"}` |
| DOM snapshot | `{after.dom_snapshot.html_path or "N/A"}` |
| Console errors | {len(after.console_errors)} |
| Network failures | {len(after.network_requests)} |

---

## Verification Details

| Metric | Before | After |
|--------|--------|-------|
| Axe violations | {v.axe_violations_before} | {v.axe_violations_after} |
| Console errors | {v.console_errors_before} | {v.console_errors_after} |
| New defects | — | {len(v.new_defects_introduced)} |
| Regressions | — | {v.regression_count} |
| Visual diff | — | {v.visual_diff_percent}% |

**Diff summary:** {v.diff_summary or "N/A"}

---

## Artifacts

| Artifact | Path |
|----------|------|
| Before screenshot | {package.before_screenshot_path or "N/A"} |
| After screenshot | {package.after_screenshot_path or "N/A"} |
| Visual diff | {package.diff_path or "N/A"} |

---

*Generated by WEBSITE-AUDITOR Proof Package Generator — P2-003 / v39*
"""


def _render_proposed_fix(fix) -> str:
    description = fix.description or "N/A"
    original = fix.original_value or "N/A"
    proposed = fix.proposed_value or "N/A"
    selectors = ", ".join(fix.affected_selectors) if fix.affected_selectors else "N/A"
    rationale = fix.rationale or "N/A"
    return f"""## Proposed Fix

| Field | Value |
|-------|-------|
| Type | {fix.fix_type} |
| Description | {description} |
| Original value | `{original}` |
| Proposed value | `{proposed}` |
| Confidence | {fix.confidence:.0%} |
| Affected selectors | {selectors} |
| Rationale | {rationale} |

---
"""


def generate_json_report(
    package: ProofPackage,
    output_dir: str | None = None,
    pretty: bool = True,
) -> str:
    """Generate a JSON report from a ProofPackage.

    Returns the path to the generated .json file.
    """
    output_dir = output_dir or tempfile.mkdtemp(prefix="website-auditor-proof-")
    os.makedirs(output_dir, exist_ok=True)

    data = package.to_dict()

    ts = datetime.now(timezone.utc).strftime("%Y%m%dT%H%M%SZ")
    json_path = os.path.join(output_dir, f"report_{ts}.json")

    indent = 2 if pretty else None
    with open(json_path, "w", encoding="utf-8") as f:
        json.dump(data, f, indent=indent, default=str)

    return json_path
