"""
Reporting engine for generating proposals in various formats.
"""

import os
import json
from typing import Dict, Any, Optional
from datetime import datetime
import logging

logger = logging.getLogger(__name__)

# Try to import optional dependencies
try:
    from jinja2 import Environment, FileSystemLoader
    JINJA2_AVAILABLE = True
except ImportError:
    JINJA2_AVAILABLE = False
    logger.warning("Jinja2 not available. Template rendering will be limited.")

try:
    import markdown
    MARKDOWN_AVAILABLE = True
except ImportError:
    MARKDOWN_AVAILABLE = False
    logger.warning("Markdown not available. Markdown processing will be limited.")

try:
    from weasyprint import HTML
    WEASYPRINT_AVAILABLE = True
except ImportError:
    WEASYPRINT_AVAILABLE = False
    logger.warning("WeasyPrint not available. PDF generation will be limited.")


class ReportingEngine:
    """Generates proposal documents in various formats."""

    def __init__(self, template_dir: str = "templates/proposals"):
        self.template_dir = template_dir
        if JINJA2_AVAILABLE:
            self.jinja_env = Environment(loader=FileSystemLoader(template_dir))
        else:
            self.jinja_env = None

    def generate_markdown(self, template_name: str, context: Dict[str, Any]) -> str:
        """
        Generate a proposal in Markdown format.
        """
        if not self.jinja_env:
            raise RuntimeError("Jinja2 not available for template rendering")

        try:
            template = self.jinja_env.get_template(f"{template_name}.md")
            markdown_content = template.render(**context)
            return markdown_content
        except Exception as e:
            logger.error(f"Failed to generate Markdown from template {template_name}: {e}")
            raise

    def generate_html(self, template_name: str, context: Dict[str, Any]) -> str:
        """
        Generate a proposal in HTML format.
        """
        if not self.jinja_env:
            raise RuntimeError("Jinja2 not available for template rendering")

        try:
            # First render as Markdown
            markdown_content = self.generate_markdown(template_name, context)

            # Convert Markdown to HTML if markdown library is available
            if MARKDOWN_AVAILABLE:
                html_content = markdown.markdown(markdown_content, extensions=['extra', 'tables'])
            else:
                # Simple fallback - wrap in basic HTML
                html_content = f"<pre>{markdown_content}</pre>"

            # Wrap in full HTML document
            full_html = f"""
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>{context.get('proposal', {}).get('title', 'Proposal')}</title>
    <style>
        body {{ font-family: sans-serif; line-height: 1.6; max-width: 800px; margin: 0 auto; padding: 20px; }}
        h1, h2, h3 {{ color: #2c3e50; }}
        table {{ border-collapse: collapse; width: 100%; margin: 20px 0; }}
        th, td {{ border: 1px solid #ddd; padding: 8px; text-align: left; }}
        th {{ background-color: #f2f2f2; }}
        .meta {{ background-color: #f8f9fa; padding: 15px; border-radius: 5px; margin: 20px 0; }}
        ul {{ padding-left: 20px; }}
    </style>
</head>
<body>
    <div class="meta">
        <strong>Business:</strong> {context.get('business', {}).get('name', 'N/A')}<br>
        <strong>Website:</strong> {context.get('website', {}).get('url', 'N/A')}<br>
        <strong>Proposal ID:</strong> {context.get('proposal', {}).get('proposal_id', 'N/A')}<br>
        <strong>Version:</strong> {context.get('proposal', {}).get('proposal_version', 'N/A')}<br>
        <strong>Date:</strong> {context.get('proposal', {}).get('created_at', datetime.now()).strftime('%Y-%m-%d')}
    </div>
    {html_content}
    <hr>
    <p><small>Generated by WEBSITE-AUDITOR Proposal Engine on {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}</small></p>
</body>
</html>
            """.strip()

            return full_html
        except Exception as e:
            logger.error(f"Failed to generate HTML from template {template_name}: {e}")
            raise

    def generate_pdf(self, template_name: str, context: Dict[str, Any], output_path: Optional[str] = None) -> bytes:
        """
        Generate a proposal in PDF format.
        Returns PDF as bytes, or writes to output_path if provided.
        """
        if not WEASYPRINT_AVAILABLE:
            logger.warning("WeasyPrint not available for PDF generation")
            # Return HTML as fallback
            html_content = self.generate_html(template_name, context)
            return html_content.encode('utf-8')

        try:
            # Generate HTML first
            html_content = self.generate_html(template_name, context)

            # Convert to PDF
            pdf_bytes = HTML(string=html_content).write_bytes()

            # Write to file if output_path provided
            if output_path:
                with open(output_path, 'wb') as f:
                    f.write(pdf_bytes)
                logger.info(f"PDF written to {output_path}")

            return pdf_bytes
        except Exception as e:
            logger.error(f"Failed to generate PDF from template {template_name}: {e}")
            raise

    def generate_proposal(self, proposal_data: Dict[str, Any],
                        template_type: str = "quick_fix",
                        format: str = "markdown") -> Any:
        """
        Generate a proposal in the specified format.
        format: "markdown", "html", or "pdf"
        """
        # Prepare context for template
        context = self._prepare_context(proposal_data)

        if format.lower() == "markdown":
            return self.generate_markdown(template_type, context)
        elif format.lower() == "html":
            return self.generate_html(template_type, context)
        elif format.lower() == "pdf":
            return self.generate_pdf(template_type, context)
        else:
            raise ValueError(f"Unsupported format: {format}")

    def _prepare_context(self, proposal_data: Dict[str, Any]) -> Dict[str, Any]:
        """
        Prepare context data for template rendering.
        """
        # Ensure we have all required fields with defaults
        context = {
            'proposal': {
                'proposal_id': proposal_data.get('proposal_id', 'PROP-0001'),
                'business_id': proposal_data.get('business_id', 'BIZ-0001'),
                'website_id': proposal_data.get('website_id', 'WEB-0001'),
                'opportunity_id': proposal_data.get('opportunity_id', 'OPP-0001'),
                'proof_id': proposal_data.get('proof_id', 'PROOF-0001'),
                'proposal_version': proposal_data.get('proposal_version', '1.0.0'),
                'pricing_version': proposal_data.get('pricing_version', '1.0.0'),
                'currency': proposal_data.get('currency', 'NZD'),
                'status': proposal_data.get('status', 'DRAFT'),
                'created_at': proposal_data.get('created_at', datetime.now()),
                'updated_at': proposal_data.get('updated_at', datetime.now())
            },
            'business': proposal_data.get('business', {
                'name': 'Unknown Business',
                'id': proposal_data.get('business_id', 'BIZ-0001')
            }),
            'website': proposal_data.get('website', {
                'url': 'https://example.com',
                'id': proposal_data.get('website_id', 'WEB-0001')
            }),
            'scope': proposal_data.get('scope', {}),
            'pricing': proposal_data.get('pricing', {}),
            'effort_confidence': proposal_data.get('effort_confidence', 'medium'),
            'pricing_calculation': proposal_data.get('pricing_calculation', {}),
            'acceptance_criteria': proposal_data.get('acceptance_criteria', []),
            'assumptions': proposal_data.get('assumptions', []),
            'exclusions': proposal_data.get('exclusions', []),
            'optional_addons': proposal_data.get('optional_addons', []),
            'evidence_refs': proposal_data.get('evidence_refs', []),
            'limitations': proposal_data.get('limitations', []),
            # Calculated fields
            'title': f"Proposal for {proposal_data.get('business', {}).get('name', 'Business')}"
        }

        return context