-- MoneyMachine Database Schema
-- Generated by mm_core.py

CREATE TABLE IF NOT EXISTS businesses (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name TEXT NOT NULL,
    region TEXT,
    public_website TEXT,
    source TEXT,
    discovered_at TEXT,
    current_status TEXT,
    is_dummy INTEGER DEFAULT 0
);

CREATE TABLE IF NOT EXISTS deals (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    business_id INTEGER NOT NULL,
    stage TEXT NOT NULL,
    updated_at TEXT,
    FOREIGN KEY (business_id) REFERENCES businesses(id)
);

CREATE TABLE IF NOT EXISTS cash (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    business_id INTEGER NOT NULL,
    amount_cents INTEGER NOT NULL,
    receipt TEXT NOT NULL,
    received_at TEXT,
    FOREIGN KEY (business_id) REFERENCES businesses(id)
);

CREATE TABLE IF NOT EXISTS messages (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    event_at TEXT NOT NULL,
    action TEXT NOT NULL,
    business_id INTEGER NOT NULL,
    detail TEXT,
    FOREIGN KEY (business_id) REFERENCES businesses(id)
);

CREATE TABLE IF NOT EXISTS receipts (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    kind TEXT NOT NULL,
    business_id INTEGER NOT NULL,
    object_id INTEGER,
    source_system TEXT,
    external_id TEXT,
    artifact_path TEXT,
    artifact_hash TEXT,
    content_hash TEXT,
    amount_cents INTEGER,
    currency TEXT DEFAULT 'NZD',
    verified_by TEXT,
    verified_at TEXT,
    occurred_at TEXT,
    verification_note TEXT,
    FOREIGN KEY (business_id) REFERENCES businesses(id)
);

CREATE TABLE IF NOT EXISTS proposals (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    business_id INTEGER NOT NULL,
    recipient TEXT NOT NULL,
    price_nzd INTEGER,
    style TEXT,
    demo_type TEXT,
    created_at TEXT,
    FOREIGN KEY (business_id) REFERENCES businesses(id)
);

CREATE TABLE IF NOT EXISTS mm_events (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    event_at TEXT NOT NULL,
    action TEXT NOT NULL,
    business_id INTEGER NOT NULL,
    detail TEXT,
    FOREIGN KEY (business_id) REFERENCES businesses(id)
);

CREATE TABLE IF NOT EXISTS mm_deals (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    business_id INTEGER NOT NULL,
    stage TEXT NOT NULL,
    updated_at TEXT,
    FOREIGN KEY (business_id) REFERENCES businesses(id)
);

CREATE TABLE IF NOT EXISTS mm_cash (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    business_id INTEGER NOT NULL,
    amount_cents INTEGER NOT NULL,
    receipt TEXT NOT NULL,
    received_at TEXT,
    FOREIGN KEY (business_id) REFERENCES businesses(id)
);

CREATE TABLE IF NOT EXISTS mm_receipts (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    kind TEXT NOT NULL,
    business_id INTEGER NOT NULL,
    object_id INTEGER,
    source_system TEXT,
    external_id TEXT,
    artifact_path TEXT,
    artifact_hash TEXT,
    verified_by TEXT,
    verified_at TEXT,
    occurred_at TEXT,
    verification_note TEXT,
    FOREIGN KEY (business_id) REFERENCES businesses(id)
);

CREATE TABLE IF NOT EXISTS mm_proposals (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    business_id INTEGER NOT NULL,
    recipient TEXT NOT NULL,
    price_nzd INTEGER,
    style TEXT,
    deadline TEXT,
    created_at TEXT,
    FOREIGN KEY (business_id) REFERENCES businesses(id)
);

CREATE TABLE IF NOT EXISTS mm_artifacts (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    business_id INTEGER NOT NULL,
    artifact_name TEXT NOT NULL,
    artifact_path TEXT,
    created_at TEXT,
    FOREIGN KEY (business_id) REFERENCES businesses(id)
);

-- Indexes for performance
CREATE INDEX IF NOT EXISTS idx_businesses_status ON businesses(current_status);
CREATE INDEX IF NOT EXISTS idx_deals_stage ON deals(stage);
CREATE INDEX IF NOT EXISTS idx_cash_business ON cash(business_id);
CREATE INDEX IF NOT EXISTS idx_messages_business ON messages(business_id);
CREATE INDEX IF NOT EXISTS idx_proposals_business ON proposals(business_id);
CREATE INDEX IF NOT EXISTS idx_mm_events_business ON mm_events(business_id);