#!/usr/bin/env python3
"""Demo Factory — local demo-page generator (scaffold).

This is a MINIMAL, dependency-free scaffold for the "Low-Touch Demo Factory"
idea: accept a short product brief and emit a structured demo page (hero,
value prop, 3 features, CTA) as Markdown. No paid APIs, no LLM calls —
generation is a pure local templating function so it always runs.

This module is importable (`from demo_factory import generate_demo`) and also
runnable as a CLI to print a demo, which makes it easy to unit-test and to
wire into a future web server or queue worker.
"""

from __future__ import annotations

import argparse
import re
import sys
from datetime import datetime, timezone


def slugify(text: str, max_len: int = 48) -> str:
    """Lowercase, dash-separated slug safe for filenames/ids."""
    slug = re.sub(r"[^a-z0-9]+", "-", (text or "").lower()).strip("-")
    return slug[:max_len] or "untitled"


def _feature_lines(brief: dict) -> list[str]:
    """Derive 3 scaffold features from the brief.

    Honest scaffold behaviour: features are template-derived from the brief
    fields, NOT invented product copy. They are placeholders to be replaced by
    a real generator (LLM/template) later.
    """
    name = brief.get("name", "Your product").strip() or "Your product"
    category = brief.get("category", "your").strip() or "your"
    one_liner = brief.get("one_liner", "").strip()

    features = [
        f"Launch in minutes — {name} is built to get {category} teams live fast, "
        f"with zero heavy setup.",
        f"Purpose-built for {category} — the workflow, language, and defaults are "
        f"tailored to how {category} operators actually work.",
    ]
    if one_liner:
        features.append(f"Built around one promise: {one_liner}")
    else:
        features.append(
            "Clear, single-minded value — one job, done well, no feature bloat."
        )
    return features[:3]


def generate_demo(brief: dict) -> str:
    """Return a Markdown demo page string for the given brief.

    `brief` keys: name (str), category (str), one_liner (str),
    audience (str, optional).
    """
    name = (brief.get("name") or "Untitled Product").strip() or "Untitled Product"
    category = (brief.get("category") or "general").strip() or "general"
    one_liner = (brief.get("one_liner") or "").strip()
    audience = (brief.get("audience") or "").strip()

    hero_sub = one_liner or f"The fastest way to ship a {category} demo."
    audience_line = f"\n\n_For: {audience}_" if audience else ""

    features = _feature_lines(brief)
    feature_md = "\n".join(f"{i}. {f}" for i, f in enumerate(features, 1))

    cta_label = "Get started"
    cta_url = brief.get("cta_url", "#").strip() or "#"

    demo = f"""# {name}

**{hero_sub}**{audience_line}

## Why {name}

{name} is a {category} tool that turns a one-line brief into a working demo.
{("It exists to " + one_liner.lower() + ".") if one_liner else "It exists to make the first impression effortless."}

## Features

{feature_md}

## Get started

[{cta_label}]({cta_url}) — try {name} today.

---
_Generated by Demo Factory (scaffold) on {datetime.now(timezone.utc).strftime('%Y-%m-%d')} · slug: `{slugify(name)}`_
"""
    return demo


def _parse_args(argv: list[str]) -> dict:
    p = argparse.ArgumentParser(description="Generate a demo page from a brief.")
    p.add_argument("--name", required=True, help="Product name")
    p.add_argument("--category", default="general", help="Product category")
    p.add_argument("--one-liner", default="", help="One-line value proposition")
    p.add_argument("--audience", default="", help="Target audience (optional)")
    p.add_argument("--cta-url", default="#", help="Call-to-action URL")
    return vars(p.parse_args(argv))


if __name__ == "__main__":
    brief = _parse_args(sys.argv[1:])
    print(generate_demo(brief))
