import json, os, subprocess, urllib.request, urllib.error
from pathlib import Path

class GitHubConnector:
    """Pushes local branches and opens Pull Requests via GitHub API."""

    def __init__(self):
        self.token = os.getenv("GITHUB_TOKEN", "")
        self.api = "https://api.github.com"

    def _headers(self):
        return {
            "Authorization": f"Bearer {self.token}",
            "Accept": "application/vnd.github+json",
            "User-Agent": "WEBSITE-AUDITOR/1.0",
        }

    def _request(self, method, endpoint, payload=None):
        url = f"{self.api}{endpoint}"
        data = json.dumps(payload).encode() if payload else None
        req = urllib.request.Request(url, data=data, headers=self._headers(), method=method)
        try:
            with urllib.request.urlopen(req) as resp:
                return {"ok": True, "status": resp.status, "body": json.loads(resp.read())}
        except urllib.error.HTTPError as e:
            return {"ok": False, "status": e.code, "error": str(e)}
        except Exception as e:
            return {"ok": False, "error": str(e)}

    def get_repo_info(self):
        """Detect repo from git remote."""
        try:
            remote = subprocess.run(
                ["git", "remote", "get-url", "origin"],
                capture_output=True, text=True, check=True
            ).stdout.strip()
            # Parse github.com:owner/repo.git or https://github.com/owner/repo.git
            if "github.com" in remote:
                path = remote.split("github.com")[-1].lstrip(":").lstrip("/")
                return path.replace(".git", "")
        except Exception:
            pass
        return None

    def push_branch(self, branch_name):
        result = subprocess.run(
            ["git", "push", "-u", "origin", branch_name],
            capture_output=True, text=True
        )
        return {"ok": result.returncode == 0, "output": result.stdout or result.stderr}

    def create_pull_request(self, title, body, head_branch, base_branch="main"):
        if not self.token:
            return {"ok": False, "error": "GITHUB_TOKEN not set. PR creation skipped (local branch only)."}

        repo = self.get_repo_info()
        if not repo:
            return {"ok": False, "error": "Could not detect GitHub repo from git remote."}

        payload = {
            "title": title,
            "body": body,
            "head": head_branch,
            "base": base_branch,
        }
        return self._request("POST", f"/repos/{repo}/pulls", payload)

    def execute_action(self, action):
        """Full flow: ensure branch pushed, then open PR."""
        branch_name = f"auto-fix/{action.action_id[:20]}"
        domain = action.domain

        # Build PR body from evidence
        pr_body = f"## 🤖 Automated Remediation\n\n"
        pr_body += f"**Domain:** {domain}\n"
        pr_body += f"**Action:** {action.name}\n"
        pr_body += f"**Risk:** {action.risk.value}\n"
        pr_body += f"**Category:** {action.category}\n\n"
        pr_body += f"### Evidence\n```json\n{json.dumps(action.payload, indent=2, default=str)}\n```\n\n"
        pr_body += f"---\n*Generated by WEBSITE-AUDITOR Action Engine*"

        # Push branch
        push_result = self.push_branch(branch_name)
        if not push_result["ok"]:
            return {"status": "local_only", "branch": branch_name, "reason": push_result.get("output", "push failed")}

        # Create PR
        pr_result = self.create_pull_request(
            title=f"fix({action.category}): {action.name} for {domain}",
            body=pr_body,
            head_branch=branch_name,
        )

        if pr_result.get("ok"):
            return {"status": "pr_created", "branch": branch_name, "pr_url": pr_result["body"].get("html_url", "")}
        else:
            return {"status": "pushed_no_pr", "branch": branch_name, "error": pr_result.get("error", "")}
