name: OSV-Scanner

on:
  pull_request:
    branches: [master]
  push:
    branches: [master]
  schedule:
    - cron: "12 12 * * 1"
  workflow_dispatch:

jobs:
  scan-pr:
    if: ${{ github.event_name == 'pull_request' }}
    permissions:
      actions: read
      contents: read
      security-events: write
    uses: google/osv-scanner-action/.github/workflows/osv-scanner-reusable-pr.yml@0c58c542420dfd23fcac08dd9c8ca3cca9c36f1a
    with:
      scan-args: |-
        --include-git-root
        -r
        ./

  scan-full:
    if: ${{ github.event_name != 'pull_request' }}
    permissions:
      actions: read
      contents: read
      security-events: write
    uses: google/osv-scanner-action/.github/workflows/osv-scanner-reusable.yml@0c58c542420dfd23fcac08dd9c8ca3cca9c36f1a
    with:
      scan-args: |-
        --include-git-root
        -r
        ./
